package main

// File was autogenerated using vscode "Go: Generate Unit Tests"

import (
	"testing"

	aoc2022 "github.com/pineman/code/chall/aoc2022/go"
)

func Test_partOne(t *testing.T) {
	type args struct {
		input []string
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{"partOne", args{aoc2022.GetInput(3)}, 8105},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := partOne(tt.args.input); got != tt.want {
				t.Errorf("partOne() = %v, want %v", got, tt.want)
			}
		})
	}
}

func Test_asciiToPriority(t *testing.T) {
	type args struct {
		item string
	}
	tests := []struct {
		name string
		args args
		want int
	}{
		{"asciiToPriority", args{"A"}, 27},
		{"asciiToPriority", args{"B"}, 28},
		{"asciiToPriority", args{"Z"}, 52},
		{"asciiToPriority", args{"a"}, 1},
		{"asciiToPriority", args{"b"}, 2},
		{"asciiToPriority", args{"z"}, 26},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := asciiToPriority(tt.args.item); got != tt.want {
				t.Errorf("asciiToPriority() = %v, want %v", got, tt.want)
			}
		})
	}
}
